/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AwardRecord: typeof import('./src/components/record/AwardRecord.vue')['default']
    AwardTable: typeof import('./src/components/table/AwardTable.vue')['default']
    ChatRecord: typeof import('./src/components/record/ChatRecord.vue')['default']
    ChatTable: typeof import('./src/components/table/ChatTable.vue')['default']
    DanmuRecord: typeof import('./src/components/record/DanmuRecord.vue')['default']
    DanmuTable: typeof import('./src/components/table/DanmuTable.vue')['default']
    EntryRecord: typeof import('./src/components/record/EntryRecord.vue')['default']
    EntryTable: typeof import('./src/components/table/EntryTable.vue')['default']
    GiftRecord: typeof import('./src/components/record/GiftRecord.vue')['default']
    GiftTable: typeof import('./src/components/table/GiftTable.vue')['default']
    GuardRecord: typeof import('./src/components/record/GuardRecord.vue')['default']
    GuardTable: typeof import('./src/components/table/GuardTable.vue')['default']
    HeaderBar: typeof import('./src/components/bar/HeaderBar.vue')['default']
    IBxsChat: typeof import('~icons/bxs/chat')['default']
    IBxsHome: typeof import('~icons/bxs/home')['default']
    InfoRecord: typeof import('./src/components/record/InfoRecord.vue')['default']
    InfoTable: typeof import('./src/components/table/InfoTable.vue')['default']
    IPhMoonBold: typeof import('~icons/ph/moon-bold')['default']
    IPhSunBold: typeof import('~icons/ph/sun-bold')['default']
    ISolarChartLineDuotone: typeof import('~icons/solar/chart-line-duotone')['default']
    LineChart: typeof import('../../EaglePlus/frontend/src/components/chart/LineChart.vue')['default']
    MedalChip: typeof import('./src/components/chip/MedalChip.vue')['default']
    PrivilegeAvatar: typeof import('./src/components/circle/PrivilegeAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TotalTable: typeof import('./src/components/table/TotalTable.vue')['default']
  }
}
